### ISSUE TITLE
API rate limit

### ISSUE THREAD

**Issue by phani-vadrevu** [PoorBillionaire/sitereview#11]
Quick question: I need to query the API for about 100,000 domains. Do you know how much time gap is recommended between consecutive queries? I tried 5-10 seconds and I feel like that is probably not sufficient as I seem to have gotten blocked.

**Comment by PoorBillionaire** [comment]
apologies for the late reply - I haven't spent any time hammering the API because it's not something I condone against a free service like sitereview.
