### ISSUE TITLE
Input Multiple domains in a file

### ISSUE THREAD

**Issue by wifiuk** [PoorBillionaire/sitereview#2]
Is it possible to feed this a list of domains from a text file? Maybe 1 per line and have it output the results to  a file ?

E.G

URL: domain1.com | Last Time Rated/Reviewed:  > 7 days | Category: Malicious Sources/Malnets

URL: http://domain2.com | Last Time Rated/Reviewed:  > 7 days | Category: Malicious S ources/Malnets

URL: http://domain3.com | Last Time Rated/Reviewed:  > 7 days | Category: Malicious S ources/Malnets

**Comment by PoorBillionaire** [comment]
Blue Coat rate-limits the amount of requests per day one can make to the Site Review web application - bulk lookups such as pulling domains from a list will quickly start failing once the web application decides you've had too much.

Otherwise, this would be an easy and useful feature to implement.

**Comment by PoorBillionaire** [comment]
Update: I just checked again, because I hadn't tested it in a while. I made 10 quick lookups. using the script. On the 11th lookup, I was prompted to complete a CAPTCHA; therefore, reading from a file wouldn't be helpful unfortunately.

**Comment by wifiuk** [comment]
How about a slight delay between posts?
