### ISSUE TITLE
Error line 49: invalid syntax

### ISSUE THREAD

**Issue by mattiabaldari** [PoorBillionaire/sitereview#4]
When I tried to execute the code, whatever input I give it returns me the following error:

File "C:\Users\USER\Desktop\sitereview-master\sitereview.py", line 49
    print "\n{0}\n{1}\n{0}\n".format(border, "Blue Coat Site Review")
                            ^
SyntaxError: invalid syntax

Am I doing something wrong or there is an error in the code?
PS: I have python 3.6.2

**Comment by PoorBillionaire** [comment]
The Sitereview script was written to only support Python 2.x, which is causing your issue when you run it with Python 3.x.

I went ahead and added Python 3.x support so you should be all set. Try it out and let me know.

--
Adam

**Comment by mattiabaldari** [comment]
Thank you! It works

Il 02 ago 2017 17:34, "Adam Witt" <notifications@github.com> ha scritto:

**Comment by PoorBillionaire** [comment]
Great, thanks for confirming. I'll close this issue out.
