### ISSUE TITLE
Seems not to work

### ISSUE THREAD

**Issue by LumingSun** [PoorBillionaire/sitereview#6]
This site uses anti-spider method now, and I think only using selenium+web driver can crawl information, but there is still a limit per IP in a period of time.

**Comment by PoorBillionaire** [comment]
The script seems to work fine for me. Can you please provide more details about what you're seeing?

**Comment by LumingSun** [comment]
Thanks for replying. I think it was because I used this .py too often in one minute so I got "Please complete the CAPTCHA". Perhaps by using proxy IP and set a waiting time could solve this problem.

**Comment by PoorBillionaire** [comment]
Oh, I see what you mean now. Yes the Site Review service has always featured rate-limiting functionality. Not to sound rude, but this has come up a couple times now and I'm not interested in helping people avoid the rate-limiting.

Symantec is undoubtedly aware that Users are scripting access to the Site Review service, and at any time could choose to modify the service to reduce this activity; by adding a captcha on each and every request, for example. For that reason I feel people who attempt to sidestep Symantec's current restrictions are behaving irresponsibly.

Finally, if you or your organization have Blue Coat proxies on-premises, IIRC, there is a local webpage/API on the device itself that you can query to obtain domain categorizations and I doubt it is rate-limited.

--
Adam

**Comment by LumingSun** [comment]
Thanks a lot!
